trigger: none

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/*

pool:
  vmImage: ubuntu-latest

jobs:
  - template: unit-tests-template.yml
  # - template: e2e-tests-template.yml
  #   parameters:
  #     k8sReleases:
  #       - "1.18"
  #     clusterConfigs:
  #       # File names in test/e2e/cluster_configs without file extension
  #       - "vmss"
  #       - "vmas"
  - template: soak-tests-template.yml
    parameters:
      clusterConfigs:
        - "pi-vmas-e2e-daily"
        - "pi-vmss-e2e-daily"
